[build]
command = "hugo"
publish = "public"

[build.environment]
HUGO_VERSION = "0.118.2"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# Redirect /post/* to /posts/*
[[redirects]]
from = "/post/*"
to = "/posts/:splat"
status = 301
force = true
